version: 2.1

# 実行環境定義
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.11.4

# ジョブ定義
jobs:
  Job1:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: "Test job1"
          command: echo "Runnning CircleCI job. ENV=$ENV"

# ワークフロー定義
workflows:
  workflow1:
    jobs:
      - Job1:
          name: "job1 in dev"
          context: evass_dev
