version: 2.1

# 実行環境定義
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.11.4

# 共通step定義
commands:
  terraform_init:
    steps:
      - checkout
      - run:
          name: "Terraform init dev"
          command: bash -ex ./scripts/terraform.sh init dev

# job定義
jobs:
  terraform_plan:
    executor:
      name: default
    steps:
      - terraform_init
      - run:
          name: "Terraform plan dev"
          command: bash -ex ./scripts/terraform.sh plan dev
  terraform_apply:
    executor:
      name: default
    steps:
      - terraform_init
      - run:
          name: "Terraform apply dev"
          command: bash -ex ./scripts/terraform.sh apply dev

# workflow定義
workflows:
  terraform_web:
    jobs:
      - terraform_plan
      - wait_approve:
          requires:
            - terraform_plan
          type: approval # plan成功したら承認待ち
      - terraform_apply:
          requires:
            - wait_approve # 承認されたら適用

# version: 2.1
# orbs:
#   terraform: 'circleci/terraform@2.1.0'
# workflows:
#   deploy_infrastructure:
#     jobs:
#       - terraform/install:
#           checkout: true
#           context: terraform
#           persist-workspace: true
#           arch: amd64
#           os: linux
#           terraform_version: 0.11.8
#       - terraform/fmt:
#           checkout: true
#           context: terraform
#       - terraform/validate:
#           checkout: true
#           context: terraform
#           requires:
#             - terraform/fmt
#       - terraform/plan:
#           checkout: true
#           context: terraform
#           persist-workspace: true
#           requires:
#             - terraform/validate
#       - terraform/apply:
#           attach-workspace: true
#           context: terraform
#           filters:
#             branches:
#               only: master
#           requires:
#             - terraform/plan
#           type: approval
